disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - trailing_comma
  - function_parameter_count
  - identifier_name
  - cyclomatic_complexity

opt_in_rules:
  - force_unwrapping

